### PR TITLE
Ensure Git index is up-to-date before dirty repo  check #37

### PR DESCRIPTION
**Pull request by jmurty**
Should fix/avoid failures seen in CI systems where the repo seems
dirty when it really isn't.

### CODE REVIEW

**Review by elasticdog — APPROVED** [review]
Nice find on the `--really-refresh` flag...this LGTM, assuming that someone from #37 can test and confirm.

**Comment by elasticdog** [comment]
This got me thinking...I wonder if this technique could replace some of the times when we "touch all encrypted files to prevent stale stat info"?

**Comment by andreineculau** [comment]
> This got me thinking...I wonder if this technique could replace some of the times when we "touch all encrypted files to prevent stale stat info"?

👏 I thought the exact same thing! I never got to test it though, but based on how I understand this to work, it should do the job just fine.

**Comment by jmurty** [comment]
Getting this moving, it should be a pretty safe change even though we haven't receive direct feedback that it fixes the problem

**Pull request merged**
