### PR TITLE
create functions for get_password() and set_password()

### PR DESCRIPTION
**Pull request by ljm42**
This makes it easier to override password handling locally
See #141

### CODE REVIEW

**Comment by jmurty** [comment]
Hi @ljm42 I like this change thanks, but I think it could be even clearer if the new functions could be called `load_password()` and `save_password()` instead of using the `get`/`set` prefixes. This would also remove the need to rename the existing `get_password()` function to `get_password_from_user()`

What do you think?

**Comment by ljm42** [comment]
Great idea! Can you squash these to a single commit? Or I could create a new PR on a clean branch if you'd like?

**Comment by jmurty** [comment]
It’s fine to make changes on this branch. I’ll squash at merge time

**Comment by ljm42** [comment]
Perfect. This should be good unless you see other issues

**Pull request merged**
