### PR TITLE
Preparations for the next release

### PR DESCRIPTION
**Pull request by jmurty**
This PR is to collect and review any changes needed to prepare for the next transcrypt release.

TODOs:

- [x] add CHANGELOG.md document
  - [x] copy old entries from GitHub release notes
  - [x] move entries from the bottom of README.md
  - [x] check for any changes worth noting that aren't yet included
-  ~~test on Windows / WSL and maybe document git alias approach from #61 in README for Windows, if that works~~
- [x] update man page documentation to reflect changes in README
  - [x] the new merge driver
  - [x] `--upgrade` command (if included)
- [x] ~~update BATS tests to always prefer single brackets `[` `]` around tests, and only use double brackets `[[` `]]` when needed for advanced features (like wildcard matching)~~
- [x] update BATS tests to always use double brackets `[[` `]]` around tests because they are safer
- [x] bump the version to `2.1.0`
- [ ] sign and push a release tag

@elasticdog please add or amend these TODOs so I can help out where I can.

### CODE REVIEW

**Comment by elasticdog** [comment]
That makes sense to me...I think it would be good to start putting changes into a legit [CHANGELOG.md](https://keepachangelog.com/en/1.0.0/) file so it's not just in the GitHub release notes (or README).

Beyond that, it's updating the docs and references like you mentioned, bumping the version, signing a tag, and then pushing it to mark a release. If you like, I can handle the signing step once you're ready, but my basic process looks like this:

    $ export GPG_TTY=$(tty)

This will tag and sign a release via GPG:

    $ git tag -s v0.9.4 -m 'Release v0.9.4'

...the signature can be verified if you have the proper public key in your GPG keyring with:

    $ git tag -v v0.9.4

You can see a tagged release with:

    $ git show v0.9.4

Push your annotated tags to the remote repo with:

    $ git push --tags

**Comment by stherold** [comment]
Hey there, when can we expect this PR to be merged roughly? For us it would be cool when https://github.com/elasticdog/transcrypt/pull/76 makes it into a new release :-)

**Comment by jmurty** [comment]
Hi @stherold we're moving slowly towards a release but we don't have a specific timeline in mind.

Be aware that you don't need to wait for an official release to take advantage of the fix in #76, you can download and use the `transcrypt` script file directly from the *master* branch and run it directly.

Here's the raw file link to the current `transcrypt` on *master*: https://raw.githubusercontent.com/elasticdog/transcrypt/master/transcrypt

**Comment by stherold** [comment]
Yup that's what I communicated in our team. This is also fine for now. Thanx fr the info :-)

**Comment by jmurty** [comment]
Hi @elasticdog I think everything in this PR is now up-to-date and we should be pretty close to being able to release version `2.1.0`, assuming that's what you want to tag it?

Can you please look over the changes here, especially the new *CHANGELOG.md* file and any new documentation or notes I have added, to make sure they are clear and correct?

**Comment by jmurty** [comment]
You're welcome @elasticdog, thanks for checking the changes.

I have pushed improvements to always use double brackets `[[` `]]` in transcrypt itself and in the tests, since it's worth it to gain any extra safety we can in bash world. I must have been confused when I added a TODO item for [the relevant comment](https://github.com/elasticdog/transcrypt/pull/89#discussion_r433860473) and got it backwards in the description of this PR.

I think it would be best to leave the contexts work to settle instead of rushing it into the 2.1.0 release, since I haven't used it at all myself day-to-day and I'm still finding rough edges and bugs in https://github.com/elasticdog/transcrypt/pull/89

**Comment by jmurty** [comment]
@elasticdog I have squash-merged this branch to `master` **without** the contexts work on #63.

Let's release!

**Comment by Blackjacx** [comment]
Wasn't this PR intended for the 2.0.0 release?

**Comment by jmurty** [comment]
Version 2.0.0 is already out: https://github.com/elasticdog/transcrypt/releases/tag/v2.0.0

**Comment by Blackjacx** [comment]
yeah I just noted down that this should be merged too for us to switch from the development (commit) version to a new tag. But since that was long ago I forgot why ^^

**Comment by elasticdog** [comment]
Sorry, I missed the original ping saying that this was merged and ready to go. I just cut a release...thanks again @jmurty!

**Comment by jmurty** [comment]
Thanks for releasing @elasticdog !

**Pull request closed without merging**
